project_id = "gpmwkgkvikvlzvqpbqus"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.create-initial-admin]
verify_jwt = false

[functions.setup-first-admin]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false

[functions.prestashop-webhook]
verify_jwt = false

[functions.opencart-webhook]
verify_jwt = false

[functions.magento-webhook]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.sync-stock]
verify_jwt = false

[functions.sync-products]
verify_jwt = false

[functions.connectix-send]
verify_jwt = false
