project_id = "gpmwkgkvikvlzvqpbqus"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.create-initial-admin]
verify_jwt = false

[functions.setup-first-admin]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false

[functions.prestashop-webhook]
verify_jwt = false

[functions.opencart-webhook]
verify_jwt = false

[functions.magento-webhook]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.sync-stock]
verify_jwt = false

[functions.sync-products]
verify_jwt = false

[functions.connectix-send]
verify_jwt = false

[functions.sync-categories]
verify_jwt = false

[functions.sync-prices]
verify_jwt = false

[functions.push-order-status]
verify_jwt = false

[functions.courier-econt]
verify_jwt = false

[functions.courier-speedy]
verify_jwt = false

[functions.courier-boxnow]
verify_jwt = false

[functions.courier-sameday]
verify_jwt = false

[functions.courier-dhl]
verify_jwt = false

[functions.courier-evropat]
verify_jwt = false

[functions.courier-cvc]
verify_jwt = false

[functions.check-login-rate]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false
